platform :ios, '8.0'

use_frameworks!

pod 'Quick', '0.3.1'
pod 'Nimble', '1.0.0-rc.1'

pod 'Wall', git: 'https://github.com/hyperoslo/Wall'
pod 'TimeAgo', git: 'https://github.com/hyperoslo/TimeAgo'
pod 'Faker', git: 'https://github.com/vadymmarkov/Faker'
